function cfg = config_analysis()
%CONFIG_ANALYSIS Common parameters and standardized paths.
%
% Python scripts write MATLAB-compatible outputs to results/. MATLAB scripts
% read those standardized outputs directly. Large public/source-data files are
% expected to be downloaded separately and placed in results/ using the names
% below; they should not be committed to GitHub.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
cfg.repoRoot = repoRoot;
cfg.resultDir = fullfile(repoRoot, 'results');
cfg.figureDir = fullfile(repoRoot, 'figures');
if ~exist(cfg.resultDir, 'dir'), mkdir(cfg.resultDir); end
if ~exist(cfg.figureDir, 'dir'), mkdir(cfg.figureDir); end

% Standardized Python outputs generated by this repository.
cfg.files.main = fullfile(cfg.resultDir, 'rnn_main.mat');
cfg.files.csOnly = fullfile(cfg.resultDir, 'rnn_cs_only.mat');
cfg.files.interval180 = fullfile(cfg.resultDir, 'rnn_interval_180s.mat');
cfg.files.inhibition = fullfile(cfg.resultDir, 'rnn_inhibition.mat');
cfg.files.stimulation = fullfile(cfg.resultDir, 'rnn_stimulation.mat');
cfg.files.stimulationNbqx = fullfile(cfg.resultDir, 'rnn_stimulation_nbqx.mat');

% Standardized MATLAB outputs.
cfg.files.clusteringOut = fullfile(cfg.resultDir, 'fixed_tsne_clustering.mat');
cfg.files.pidOut = fullfile(cfg.resultDir, 'decoder_pid_results.mat');
cfg.files.trajectoryOut = fullfile(cfg.resultDir, 'pca_trajectory_results.mat');
cfg.files.stimOut = fullfile(cfg.resultDir, 'stimulation_summary.mat');
cfg.files.trajectoryVisualizationOut = fullfile(cfg.resultDir, 'rnn_trajectory_visualization.mat');
cfg.files.nonlinearOut = fullfile(cfg.resultDir, 'nonlinear_trajectory_prediction.mat');
cfg.files.crossTemporalOut = fullfile(cfg.resultDir, 'cross_temporal_decoding.mat');
cfg.files.gpfaOut = fullfile(cfg.resultDir, 'biological_gpfa_trajectories.mat');

% Standardized public/source-data inputs derived from the deposited data bundle.
cfg.files.publicRnnActivity = fullfile(cfg.resultDir, 'rnn_activity_public.mat');
cfg.files.publicPerturbations = fullfile(cfg.resultDir, 'rnn_perturbations_public.mat');
cfg.files.publicPidSynergy = fullfile(cfg.resultDir, 'rnn_pid_synergy_public.mat');
cfg.files.publicGpfaInput = fullfile(cfg.resultDir, 'biological_gpfa_public.mat');
cfg.files.publicClusterOut = cfg.files.clusteringOut;

% Timing is expressed in MATLAB bins after Python export. In these files one
% bin corresponds to one second in the analysis.
cfg.timing.dt = 1;
cfg.timing.totalSize = 240;
cfg.timing.cueStart = 70;
cfg.timing.csDuration = 20;
cfg.timing.doorDelayBins = 25;        % cue onset to door opening in the 5-s interval condition
cfg.timing.baselineLength = 30;
cfg.timing.afterCross = 5;
cfg.timing.crossThreshold = 0.5;

% t-SNE parameters reported in the manuscript. No parameter sweep is
% performed in this repository.
cfg.tsne.perplexity = 24;
cfg.tsne.exaggeration = 48;
cfg.tsne.numDimensions = 3;
cfg.tsne.rngSeed = 1;
cfg.tsne.maxIter = 1000;
cfg.tsne.distance = 'cosine';
cfg.tsne.learnRate = 100;

% Cluster labels in the representative network. The k-means label of the
% claustrum-like cluster is 2; figures label this as published Cluster 1.
cfg.cluster.claustrumLikeCluster = 2;
cfg.cluster.publishedOrder = [2 1 3];  % published C1, C2, C3 -> k-means labels
cfg.cluster.maxClusters = 5;
cfg.cluster.kmeansReplicates = 50;

% Time normalization used by decoder, PID, and trajectory analyses.
cfg.pid.analysisStartOffset = 40;
cfg.pid.fixedPreOpenBins = 55;
cfg.pid.meanCrossBins = 30;
cfg.pid.fixLen = cfg.pid.fixedPreOpenBins + cfg.pid.meanCrossBins;
cfg.pid.decoderSmoothWindow = 15;
cfg.pid.roundDigits = 1;

% PCA trajectory visualization mirrors the deposited public analysis files.
cfg.trajectory.cropStartBin = 40;
cfg.trajectory.fixedPreOpenBins = 55;
cfg.trajectory.postOpenBins = 30;
cfg.trajectory.smoothing = true;

% Nonlinear trajectory-prediction analysis.
cfg.rss.hiddenSize = [6 3];
cfg.rss.regularizationCandidates = [0 0.25 0.5 0.75 1];
cfg.rss.lambdaSweeps = 5;
cfg.rss.mlpRepeats = 10;

% Stimulation-only simulations occur in an early window and are independent
% of CS/door inputs. Python uses 200:210 in PsychRNN units, corresponding to
% bin 21 in exported MATLAB arrays.
cfg.stimulation.startBin = 21;
cfg.stimulation.baselineLength = 5;
end
